### ISSUE TITLE
Notification not working as Expected.

### ISSUE THREAD

**Issue by dpz3579** [priyal25/LocalNotificationReact#1]
https://github.com/priyal25/LocalNotificationReact/blob/d735fa3332a4c0c0fa6148e925869bede19a8951/LocalNotificationDemo/ios/LocalNotificationManager.m#L31

Hi,

The App is not working as Expected.

1. The Notification is appearing after a delay of 5 Seconds.
2. The Notifications does not appear in the notification tray when the app is running.

**Comment by priyal25** [comment]
Hi, 

1. I have added a delay of 5 seconds to avoid any haphazard scenario, though I can show notification as soon as the user taps the button if required. 
2.  When the app is in foreground notification will not be displayed in the tray as app should itself handle and pass the data, as stated [here](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/).

**Comment by dpz3579** [comment]
Hi @priyal25 ,

1. Yes, we want an instant notification when I click on the button.
2. I do agree with the fact that notification should not be shown when the app is running in the foreground, but our use case scenario is that I want a notification, even though the user is using the app. (i.e. the notification should show in notification tray even if my app is running in the foreground)

**Comment by priyal25** [comment]
Hi,
I have updated the code and resolved both the issues.
